### PR TITLE
fixed erratic radius for asset references under certain circumstances

### PR DESCRIPTION
**Pull request by tbd-vam**

### CODE REVIEW

**Comment by Yoooi0** [comment]
I'm assuming this is about the case when up direction is set to "-Up"? Could not reproduce any other circumstances.
If so then the better fix would be to handle "-Up" as special case since `Quaternion.FromToRotation` breaks when the parameters are opposite.
Probably like so:
```csharp
            if (UpDirectionChooser.val == "-Up")
            {
                Up = -transform.up;
                Right = -transform.right;
                Forward = -transform.forward;
            }
            else
            {
                var upRotation = Quaternion.FromToRotation(transform.up, newUp);

                Up = upRotation * transform.up;
                Right = upRotation * transform.right;
                Forward = upRotation * transform.forward;
            }
```

Your fix also causes the radius to go out of mesh bounds.
The radius should also probably be a minimum of Right and Forward projected extent.
```csharp
            var worldExtents = transform.rotation * bounds.extents;
            var rightProjectedExtents = Vector3.Project(worldExtents, Right).magnitude;
            var forwardProjectedExtents = Vector3.Project(worldExtents, Forward).magnitude;
            Radius = Mathf.Min(rightProjectedExtents, forwardProjectedExtents);
```

**Comment by tbd-vam** [comment]
Try the orientation I posted out in the other PR. The bug happens because the transform rotates in the opposite direction to the bounding box if it's pointing down. That means the vectors that are being projected alternate between being parallel and orthogonal, causing the radius calculation to oscillate.

> Your fix also causes the radius to go out of mesh bounds.

It changes the radius from the inside bound to the outside bound. Instead of the box's edges being tangent to the circle it now touches the corners (the new radius is the diagonal).
Arguably, it even makes sense to use the bounding box's outside dimensions as the "size" of the object.

There's no need to change anything else about the code besides the radius calculation. In fact, besides the radius being the diagonal, nothing has changed.

```
            if (UpDirectionChooser.val == "-Up")
            {
                Up = -transform.up;
                Right = -transform.right;
                Forward = -transform.forward;
            }
            else
            {
                var upRotation = Quaternion.FromToRotation(transform.up, newUp);

                Up = upRotation * transform.up;
                Right = upRotation * transform.right;
                Forward = upRotation * transform.forward;
            }
```


I made no functional change to this part of the code and I see no reason why it could break.

**Comment by tbd-vam** [comment]
```
            var worldExtents = transform.rotation * bounds.extents;
            var rightProjectedExtents = Vector3.Project(worldExtents, Right).magnitude;
            var forwardProjectedExtents = Vector3.Project(worldExtents, Forward).magnitude;
            Radius = Mathf.Min(rightProjectedExtents, forwardProjectedExtents);
```

This doesn't solve the bug. Both the Right and Forward vectors rotate relative to the extents vector.

Here's a video of the bug in action with the v18 release code and two additional lines in the debug draw. The extents vector and the calculated radius vector ``Vector3.Project(transform.rotation * bounds.extents, Right)`` in magenta.
[https://mega.nz/file/acRAFIqD#OZ2G0_za_dd-ZXJSBMNLNX-l69jUqWvLyhlirsvWDf0](mega)
Note the opposite rotation

**Comment by Yoooi0** [comment]
I meant that the current bug exists because of `Quaternion.FromToRotation` when the direction is set to "-Up". At least this is exactly the same issue I reproduced as in your video. 

So the solution is to handle the special "-Up" case instead of setting the radius to make an exact circumscribed circle of the extents. Changing the radius code does solve the radius oscillating but does not fix the real bug. You can see that the debug draw breaks where right/forward vectors rotate in opposite direction of the model rotation.


The second part was me just pointing out that the current code (`Vector3.Project(transform.rotation * bounds.extents, Right)`) is oversimplified. I think it should be an inner radius (min of right/forward) as outer radius (your code) will make the reference radius very large given the default 300% scale. Could maybe be a toggle or something. But technically outside of scope of this fix/PR.

**Comment by Yoooi0** [comment]
Ok, I just pushed a fix real quick, so closing.

**Pull request closed without merging**
